# Variables in task level
- name: writing variables as per task level
  hosts: localhost
  vars: 
    name: Lokesh
    course: project-k
    duration: 2months
  tasks:
  - name: writing variables in task level
    ansible.builtin.debug:
      msg: "Hi this is {{name}} doing the {{course}} in the time of {{duration}}"
