- name: Writing for prompt code 
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter the username
    private: false
  - name: PASSWORD
    prompt: please enter the password
    private: true 
  tasks:
  - name: Validation checks whether prompt is executing or not
    ansible.builtin.debug: 
      msg: "username is: {{USERNAME}}, password is {{PASSWORD}}" 
    