- name: Writing for prompt code 
  hosts: localhost
  vars_prompt:
  - name: Giving the username
    prompt: please enter the username
    private: false
  - name: Giving the password
    prompt: please enter the password
    private: true 
  tasks:
  - name: Validation checks whether prompt is executing or not
    ansible.builtin.debug: 
      msg: "username is: {{Giving the username}}, password is {{Giving the password}}" 