- name: writing variables from args - CMD
  hosts: localhost
  tasks: 
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi this is {{mars}} doing the {{earth}} in the time of {{moon}}"






      